image: node:20.10.0-alpine3.18

before_script:
  - npm ci

cache:
  policy: pull-push
  paths:
    - node_modules/

stages:
  - test
  - lint
  - build

test:
  stage: test
  script:
    - npm run test

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - web-ext-artifacts/
